version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=$MYSQL_DB
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - gutenberg-network
    ports:
      - "3306:3306"

  wordpress:
    depends_on:
      - db
    image: wordpress:php7.4-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    # Настройка в локльном файле .conf/wordpress/wp-config.php
    volumes:
      - site_root:/var/www/html
      - ./.conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./.conf/wordpress/wp-config.php:/var/www/html/wp-config.php
      - ./.conf/php/test.php:/var/www/html/test.php
      - ./updraft:/var/www/html/wp-content/updraft
      - ./themes/blockbase:/var/www/html/wp-content/themes/blockbase
      - ./themes/blocksy:/var/www/html/wp-content/themes/blocksy
      - ./plugins/gutenberg:/var/www/html/wp-content/plugins/gutenberg
      - ./plugins/qubely:/var/www/html/wp-content/plugins/qubely
      - ./plugins/wpsitesynccontent:/var/www/html/wp-content/plugins/wpsitesynccontent
    networks:
      - gutenberg-network

  nginx:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - site_root:/var/www/html
      - ./.conf/nginx:/etc/nginx/conf.d
      - ./.conf/ssl/cert.pem:/etc/nginx/cert.pem
      - ./.conf/ssl/server.key:/etc/nginx/server.key 
      - ./.conf/php/test.php:/var/www/html/test.php
      - ./updraft:/var/www/html/wp-content/updraft
      - ./themes/blockbase:/var/www/html/wp-content/themes/blockbase
      - ./themes/blocksy:/var/www/html/wp-content/themes/blocksy
      - ./plugins/gutenberg:/var/www/html/wp-content/plugins/gutenberg
      - ./plugins/qubely:/var/www/html/wp-content/plugins/qubely
      - ./plugins/wpsitesynccontent:/var/www/html/wp-content/plugins/wpsitesynccontent      
    networks:
      - gutenberg-network

volumes:
  dbdata:
  site_root:

networks:
  gutenberg-network:
    driver: bridge
