version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=$MYSQL_DB
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network
    ports:
      - "3306:3306"

  wordpress:
    depends_on:
      - db
    image: wordpress:5.1.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_DB
    volumes:
      - site_root:/var/www/html  
    networks:
      - app-network

  nginx:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.conf/nginx:/etc/nginx/conf.d
      - ./.conf/ssl/cert.pem:/etc/nginx/cert.pem
      - ./.conf/ssl/server.key:/etc/nginx/server.key  
      - site_root:/var/www/html 
    networks:
      - app-network

volumes:
  site_root:
  dbdata:

networks:
  app-network:
    driver: bridge
